services:

  service_a:
    image: jboss/wildfly:latest
    container_name: service_a
    ports:
      - "8080:8080"
    cpuset: '0'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1024M'
    volumes:
      - ./target/ROOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war

  service_b:
    image: jboss/wildfly:latest
    container_name: service_b
    ports:
      - "8081:8080"
    cpuset: '4'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1024M'
    volumes:
      - ./target/ROOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war
